/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.dartmouth.bt.planon.helloworld;

import nl.planon.hades.userextension.uxinterface.*;

public abstract class HelloWorld implements IUserExtension {
    private String description = "This User Extension sets the value of a free field on the business object.";

    public HelloWorld(String description) {
        this.description = description;
    }

    public void executeUX(IUXBusinessObject newBO, IUXBusinessObject oldBO, IUXContext context, String parameters) {
        String helloworld = "hello!";

        IUXStringField FreeString11 = newBO.getStringFieldByName("FreeString11");
        
        FreeString11.setValueAsString(helloworld);
        newBO.save();
    }
    
    public String getDescription() {
        return this.description;
    }
}