/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.dartmouth.bt.planon.helloworld;

import nl.planon.hades.userextension.uxinterface.*;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
