/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.dartmouth.bt.planon;

import nl.planon.hades.userextension.uxinterface.*;

public class HelloWorld implements IUserExtension {
    private String description = "This is the description that is shown to administrators in the Planon web client.";

    public HelloWorld() {}

    public void executeUX(IUXBusinessObject newBO,IUXBusinessObject oldBO, IUXContext context, String parameter) {
        // do stuff
    }
    
    public String getDescription() {
        return description;
    }
}